name: Main Config
version: 1.0.0
schema: v1
models:
  - name: Qwen3 14B - GPU
    provider: ollama
    model: Qwen3-14B
    apiBase: http://127.0.0.1:11434
    roles:
      - chat
      - edit
      - apply

  - name: Qwen3 8B - NPU
    provider: ollama
    model: Qwen3-8B-int4-cw
    apiBase: http://127.0.0.1:11434
    roles:
      - chat
      - edit
      - apply
      - autocomplete