const TICK_MS = Number(process.env.SERVER_TICK_MS) || 50; // 20 ticks per second
const MAX_PLAYERS_PER_MATCH = Number(process.env.MAX_PLAYERS_PER_MATCH) || 10;
const MAX_LOBBY_PLAYERS = MAX_PLAYERS_PER_MATCH;
// Require exactly 10 players per match by default (can be overridden via env)
const MIN_PLAYERS_TO_START = Number(process.env.MIN_PLAYERS_TO_START) || 2;
// Default lobby countdown (ms) when minimum players reached — set to 30s
const MATCHMAKING_TIMEOUT_MS = Number(process.env.MATCHMAKING_TIMEOUT_MS) || 30000;
const LOBBY_COUNTDOWN_MS = MATCHMAKING_TIMEOUT_MS;
const PLAYER_RECONNECT_MS = Number(process.env.RECONNECT_TIMEOUT_MS) || 30000;
const MATCH_MAX_DURATION_MS = Number(process.env.MATCH_MAX_DURATION_MS) || 5 * 60 * 1000; // 5 minutes
const LANE_COUNT = 4;
const TEMP_MIN = 8;
const TEMP_MAX = 32;
const TEMP_SAFE_LO = 12;
const TEMP_SAFE_HI = 20;
const TEMP_START = 15;
const MAX_LANE_DELTA = 1;
const MAX_HIT_COOLDOWN = 300;
const MAX_BURST_COOLDOWN = 80;
const MAX_BURROW_COOLDOWN = 180;
const MAX_JUMP_COOLDOWN = 80;
const MAX_ATTACK_COOLDOWN = 120;
const MAX_INPUTS_PER_SECOND = 45;
const ATTACK_RANGE = 1;
const JUMP_HEIGHT = 18;
const MAX_PREDATOR_DELAY = 24; // ticks

module.exports = {
  TICK_MS,
  MAX_PLAYERS_PER_MATCH,
  MAX_LOBBY_PLAYERS,
  MIN_PLAYERS_TO_START,
  MATCHMAKING_TIMEOUT_MS,
  LOBBY_COUNTDOWN_MS,
  PLAYER_RECONNECT_MS,
  MATCH_MAX_DURATION_MS,
  LANE_COUNT,
  TEMP_MIN,
  TEMP_MAX,
  TEMP_SAFE_LO,
  TEMP_SAFE_HI,
  TEMP_START,
  MAX_LANE_DELTA,
  MAX_HIT_COOLDOWN,
  MAX_BURST_COOLDOWN,
  MAX_BURROW_COOLDOWN,
  MAX_JUMP_COOLDOWN,
  MAX_ATTACK_COOLDOWN,
  MAX_INPUTS_PER_SECOND,
  ATTACK_RANGE,
  JUMP_HEIGHT,
  MAX_PREDATOR_DELAY
};